services:
    # -- DATA TRANSFORMERs --
    api.data_transformer.product_data_transformer:
        class: ApiBundle\DataTransformer\ProductDataTransformer
        arguments:
            - "@doctrine.orm.entity_manager"