parameters:
    parsing.cache_dir: "%kernel.root_dir%/../var/parser/"
    parsing.phantom_dir: "%kernel.root_dir%/../src/ParsingBundle/Service/phantomjs"

services:
    parsing.proxy_list:
        class: ParsingBundle\Service\ProxyList
        arguments: ["@doctrine.orm.entity_manager"]

    parsing.yandex_market:
        class: ParsingBundle\Service\YandexMarketParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - "%proxy_userpasswd%"
            - "%parsing.phantom_dir%/yandex_market.js"

    parsing.yandex_market_redirect:
        class: ParsingBundle\Service\YandexMarketRedirectParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - "%proxy_userpasswd%"
            - "%parsing.phantom_dir%/yandex_market.js"

    parsing.yandex_market_check_again:
        class: ParsingBundle\Service\YandexMarketCheckAgainParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - "%proxy_userpasswd%"
            - "%parsing.phantom_dir%/yandex_market.js"

    parsing.pcpartpicker:
        class: ParsingBundle\Service\PcpartpickerParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - ""
            - ""

    parsing.pcpartpicker_product_info:
        class: ParsingBundle\Service\PcpartpickerProductInfoParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - "%proxy_userpasswd%"
            - "%parsing.phantom_dir%/yandex_market.js"

    parsing.benchmark:
        class: ParsingBundle\Service\BenchmarkParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - ""
            - ""

    parsing.all_free_proxy:
        class: ParsingBundle\Service\AllFreeProxyParser
        arguments: ["@service_container"]

    parsing.spys:
        class: ParsingBundle\Service\SpysFreeProxyParser
        arguments: ["@doctrine.orm.entity_manager", "@parsing.proxy_list", "%parsing.cache_dir%", "%rucaptcha_token%"]

    parsing.phantom.client:
        class: ParsingBundle\Service\PhantomJSClient
        arguments: ["%parsing.phantom_dir%"]
