parameters:
    parsing.cache_dir: "%kernel.root_dir%/../var/parser/"
    parsing.phantom_dir: "%kernel.root_dir%/../src/ParsingBundle/Service/phantomjs"

services:
    parsing:
        class: ParsingBundle\Service\BaseParser
        arguments:
            index_0: "@doctrine.orm.entity_manager"
            index_1: "@parsing.proxy_list"
            index_2: "%parsing.cache_dir%"
            index_3: "%rucaptcha_token%"
            index_4: "%proxy_userpasswd%"
            index_5: ''
            index_6: '@product_handler'

        abstract: true

    parsing.proxy_list:
        class: ParsingBundle\Service\ProxyList
        arguments: ["@doctrine.orm.entity_manager"]

    parsing.yandex_market:
        class: ParsingBundle\Service\YandexMarketParser
        parent: parsing
        arguments:
            index_5: "%parsing.phantom_dir%/yandex_market.js"

    parsing.yandex_market_redirect:
        class: ParsingBundle\Service\YandexMarketRedirectParser
        parent: parsing
        arguments:
            index_5: "%parsing.phantom_dir%/yandex_market.js"

    parsing.yandex_market_check_again:
        class: ParsingBundle\Service\YandexMarketCheckAgainParser
        parent: parsing
        arguments:
            index_5: "%parsing.phantom_dir%/yandex_market.js"

    parsing.pcpartpicker:
        class: ParsingBundle\Service\PcpartpickerParser
        parent: parsing

    parsing.pcpartpicker_product_info:
        class: ParsingBundle\Service\PcpartpickerProductInfoParser
        parent: parsing
        arguments:
            index_5: "%parsing.phantom_dir%/yandex_market.js"

    parsing.benchmark:
        class: ParsingBundle\Service\BenchmarkParser
        parent: parsing

    parsing.benchmark_search:
        class: ParsingBundle\Service\BenchmarkSearchParser
        parent: parsing

    parsing.all_free_proxy:
        class: ParsingBundle\Service\AllFreeProxyParser
        arguments: ["@service_container"]

    parsing.spys:
        class: ParsingBundle\Service\SpysFreeProxyParser
        parent: parsing

    parsing.phantom.client:
        class: ParsingBundle\Service\PhantomJSClient
        arguments: ["%parsing.phantom_dir%"]

    parsing.avito:
        class: ParsingBundle\Service\AvitoParser
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parsing.proxy_list"
            - "%parsing.cache_dir%"
            - "%rucaptcha_token%"
            - "%proxy_userpasswd%"
            - ""
            - '@product_handler'
            - '@repo.offer'
            - "@request_object_handler"
            - "@repo.parsing_site"
            - "@avito_date_parser"
            - '@repo.product_type'
            - '@offer_handler'

    repo.parsing_site:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - ParsingBundle\Entity\ParsingSite

    avito_date_parser:
        class: ParsingBundle\Service\AvitoDateParser
        autowire: true