parameters:
    parsing.cache_dir: "%kernel.root_dir%/../var/parser/"
    parsing.phantom_dir: "%kernel.root_dir%/../src/ParsingBundle/Service/phantomjs"

services:
    parsing.proxy_list:
        class: ParsingBundle\Service\ProxyList
        arguments: ["@doctrine.orm.entity_manager"]

    parsing.yandex_market:
        class: ParsingBundle\Service\YandexMarketParser
        arguments: ["@doctrine.orm.entity_manager", "@parsing.proxy_list", "%parsing.cache_dir%", "%rucaptcha_token%"]

    parsing.all_free_proxy:
        class: ParsingBundle\Service\AllFreeProxyParser
        arguments: ["@service_container"]

    parsing.spys:
        class: ParsingBundle\Service\SpysFreeProxyParser
        arguments: ["@doctrine.orm.entity_manager", "@parsing.proxy_list", "%parsing.cache_dir%", "%rucaptcha_token%"]

    parsing.phantom.wrap:
        class: ParsingBundle\Service\PhantomJSWrapper
        arguments: ["%parsing.phantom_dir%"]
