services:
    parsing.proxy_list:
        class: ParsingBundle\Service\ProxyList
        arguments: ["@doctrine.orm.entity_manager"]

    parsing.yandex_market:
        class: ParsingBundle\Service\YandexMarketParser
        arguments: ["@doctrine.orm.entity_manager", "@parsing.proxy_list"]
