<?php

namespace ParsingBundle\Repository;

use ProductBundle\Repository\BaseRepo;

/**
 * ParsingSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParsingSiteRepository extends BaseRepo
{
}
