<?php

namespace ParsingBundle\Repository;

/**
 * ParsingSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParsingSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
