<?php

namespace ParsingBundle\Repository;

/**
 * ParsingProductInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParsingProductInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
