<?php

namespace ParsingBundle\Repository;

/**
 * ProxyIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyIpRepository extends \Doctrine\ORM\EntityRepository
{
}
