<?php

namespace ParsingBundle\Repository;

use ProductBundle\Repository\BaseRepo;

/**
 * ProxyIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyIpRepository extends BaseRepo
{
}
