<?php

namespace ComputerBundle\Repository;

/**
 * ComputerProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerProductRepository extends \Doctrine\ORM\EntityRepository
{
}
