<?php

namespace ProductBundle\Repository;

/**
 * AtrributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtrributeRepository extends \Doctrine\ORM\EntityRepository
{
}
