<?php

namespace ProductBundle\Repository;

/**
 * AttributeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
