<?php

namespace ProductBundle\Repository;

/**
 * AvitoOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvitoOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
