<?php

namespace ProductBundle\Repository;
use ProductBundle\Entity\Product;
use ProductBundle\RequestObjects\GetOneProductRequest;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseRepo
{
}
